spring.application.name=BotMonitoringBE
spring.data.mongodb.uri=mongodb://172.16.20.55:27017/bot-monitoring-test-Demo
app.cors.allowed-origin=http://localhost:3000
#file.upload-dir= ${user.home}/BHIMS-FILES/
file.upload-dir=D:/BHIMS-FILES/
server.address=0.0.0.0
server.port=8880
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=1800000
