<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.ahana.botmonitoring</groupId>
	<artifactId>rpm-bot-monitoring</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>rpm-bot-monitoring</name>
	<description>RPM Bot Monitoring System.</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<lombok.version>1.18.30</lombok.version>
		<maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
		<openapi-generator-maven-plugin.version>7.0.0</openapi-generator-maven-plugin.version>
		<jackson.databind.nullable>0.2.6</jackson.databind.nullable>
		<jackson.fasterxml.version>2.15.0</jackson.fasterxml.version>
		<springdoc-openapi-ui.version>2.2.0</springdoc-openapi-ui.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.10.1</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.11.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.11.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson.databind.nullable}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
			<version>${jackson.fasterxml.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>${jackson.fasterxml.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson.fasterxml.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.fasterxml.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc-openapi-ui.version}</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.15</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.plugin.version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-generator-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-common-model</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/common.yml</inputSpec>
							<generatorName>spring</generatorName>
							<addCompileSourceRoot>true</addCompileSourceRoot>
							<modelPackage>com.ahana.botmonitoring.generated.model</modelPackage>
							<packageName>com.ahana.botmonitoring.generated</packageName>
							<generateApiDocumentation>false</generateApiDocumentation>
							<generateApiTests>false</generateApiTests>
							<generateModelDocumentation>true</generateModelDocumentation>
							<generateModelTests>true</generateModelTests>
							<generateModels>true</generateModels>
							<additionalProperties>removeEnumValuePrefix=false</additionalProperties>
							<configOptions>
								<generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
								<useTags>true</useTags>
								<interfaceOnly>true</interfaceOnly>
								<useSpringBoot3>true</useSpringBoot3>
								<delegatePattern>true</delegatePattern>
								<useSpringController>true</useSpringController>
								<dateLibrary>java8-localdatetime</dateLibrary>
								<additionalModelTypeAnnotations>
									@lombok.NoArgsConstructor
									@lombok.Builder(toBuilder=true)
									@lombok.AllArgsConstructor
									@lombok.Generated
									@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
								</additionalModelTypeAnnotations>
							</configOptions>
							<output>${project.build.directory}/generated-sources/common</output>
						</configuration>
					</execution>
					<execution>
						<id>generate-rpm-bot-monitoring-api</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/rpm-bot-monitoring.yml</inputSpec>
							<generatorName>spring</generatorName>
							<addCompileSourceRoot>true</addCompileSourceRoot>
							<apiPackage>com.ahana.botmonitoring.generated.api</apiPackage>
							<modelPackage>com.ahana.botmonitoring.generated.model</modelPackage>
							<packageName>com.ahana.botmonitoring.generated</packageName>
							<generateApiDocumentation>true</generateApiDocumentation>
							<generateApiTests>true</generateApiTests>
							<generateModels>false</generateModels>
							<generateModelDocumentation>false</generateModelDocumentation>
							<generateModelTests>false</generateModelTests>
							<additionalProperties>removeEnumValuePrefix=false</additionalProperties>
							<configOptions>
								<generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
								<useTags>true</useTags>
								<interfaceOnly>true</interfaceOnly>
								<useSpringBoot3>true</useSpringBoot3>
								<delegatePattern>true</delegatePattern>
								<useSpringController>true</useSpringController>
								<dateLibrary>java8-localdatetime</dateLibrary>
								<modelInheritanceSupport>true</modelInheritanceSupport>
								<UseOneOfInterface>true</UseOneOfInterface>
							</configOptions>
							<output>${project.build.directory}/generated-sources/rpm-bot-monitoring</output>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>



</project>
